apiVersion: v2
name: services
description: MyNextPay Tech Helm chart application

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

dependencies:
  - name: frontend-project
    version: 0.1.0
    condition: frontend-project.enabled
  - name: backend-project
    version: 0.1.0
    condition: backend-project.enabled
  - name: kafka-event-manager
    version: 0.1.0
    condition: kafka-event-manager.enabled
  - name: rethink-db
    version: 0.1.0
    condition: rethink-db.enabled
  - name: my-nextpay-tech-chat
    version: 0.1.0
    condition: my-nextpay-tech-chat.enabled
  - name: tags-api
    version: 0.1.0
    condition: tags-api.enabled
  - name: media-server
    version: 0.1.0
    condition: media-server.enabled
  - name: backlog-services
    version: 0.1.0
    condition: backlog-services.enabled
  - name: fe-storage-services
    version: 0.1.0
    condition: fe-storage-services.enabled
  - name: redis
    version: 0.1.0
    condition: redis.enabled
  - name: telegram-bot
    version: 0.1.0
    condition: telegram-bot.enabled
  - name: history-service
    version: 0.1.0
    condition: history-service.enabled
  - name: feeds
    version: 0.1.0
    condition: feeds.enabled
  - name: incident
    version: 0.1.0
    condition: incident.enabled
  - name: socket-noti-server
    version: 0.1.0
    condition: socket-noti-server.enabled
  - name: response-team-service
    version: 0.1.0
    condition: response-team-service.enabled
  - name: incident-tracking
    version: 0.1.0
    condition: incident-tracking.enabled
  - name: chat-service
    version: 0.1.0
    condition: chat-service.enabled
  - name: demo-integrated-service
    version: 0.1.0
    condition: demo-integrated-service.enabled
